name: Save GitHub Traffic Data Daily

on:
  schedule:
    - cron: '0 0 * * *' # Runs automatically every night at midnight UTC
  workflow_dispatch: # Allows you to manually click a button to run it anytime

jobs:
  run-traffic-collector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Fetch traffic metrics
        uses: jasonetco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TRAFFIC_TOKEN }}

      - name: GitHub Repo Stats
        uses: gayanvoice/github-stats-action@v1
        with:
          token: ${{ secrets.TRAFFIC_TOKEN }}
